// source: https://foodisgood.com/support/which-dietary-needs-and-preferences-are-supported-by-fig/

export const tags = [
  "Alpha Gal",
  "Autoimmune Protocol",
  "Candida Overgrowth",
  "Citric Acid Intolerance",
  "Dairy Free",
  "Egg Free",
  "Emulsifier Free",
  "Fructose Free",
  "GERD (acid reflux)",
  "Gluten Free",
  "Interstitial Cystitis",
  "Lactose Free",
  "Low FODMAP",
  "Low Histamine",
  "Low Iodine",
  "Low Residue",
  "Mediterranean Diet",
  "No beef",
  "No pork",
  "No poultry",
  "Paleo",
  "Pescatarian",
  "Pregnancy",
  "Vegan",
  "Vegetarian",
  "Barley allergy",
  "Celery allergy",
  "Citrus fruit allergy",
  "Corn allergy",
  "Egg allergy",
  "Fish allergy",
  "Latex food allergy",
  "Lupin allergy",
  "Milk allergy",
  "Mustard allergy",
  "Nickel allergy",
  "Oats allergy",
  "Peanut allergy",
  "Pollen food allergy",
  "Rice allergy",
  "Rye allergy",
  "Seed allergy",
  "Sesame allergy",
  "Seafood allergy",
  "Soy allergy",
  "Tree nut allergy",
  "Wheat allergy",
];
